name: CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Check formatting and compilation
      run: cargo check --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Build release binary
      run: cargo build --release --verbose
